### PR TITLE
new files for boxfill and isofill anim tests

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
goes with: https://github.com/UV-CDAT/uvcdat/pull/1236

**Comment by aashish24** [comment]
whats changed here?

**Comment by doutriaux1** [comment]
new baselines files for tests for boxfill/isofill animation, the latest update had broken boxfill animation (only white frames) see: https://github.com/UV-CDAT/uvcdat/pull/1236

**Comment by doutriaux1** [comment]
so I added tests to also look at boxfill and isofill animations

**Pull request merged**
