### PR TITLE
new baseline agains proj 4.9.2

### PR DESCRIPTION
**Pull request by doutriaux1**
@danlipsa aeq baselines

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 These are different compared with the old baselines -beyond the font differences. You might have missed them.
test_vcs_basic_boxfill_aeqd_proj_SH.png
test_vcs_basic_boxfill_aeqd_proj_SH_-180_180.png
test_vcs_basic_boxfill_aeqd_proj_SH_-180_180_via_gm.png
test_vcs_basic_boxfill_aeqd_proj_SH_0_360.png
test_vcs_basic_boxfill_aeqd_proj_SH_0_360_via_gm.png
test_vcs_basic_boxfill_aeqd_proj_SH_via_gm.png
test_vcs_basic_isofill_masked_aeqd_proj_1.png
test_vcs_basic_meshfill_aeqd_proj_SH.png
test_vcs_basic_meshfill_aeqd_proj_SH_-180_180.png
test_vcs_basic_meshfill_aeqd_proj_SH_-180_180_via_gm.png
test_vcs_basic_meshfill_aeqd_proj_SH_0_360.png
test_vcs_basic_meshfill_aeqd_proj_SH_0_360_via_gm_1.png
test_vcs_basic_meshfill_aeqd_proj_SH_0_360_via_gm_2.png
test_vcs_basic_meshfill_aeqd_proj_SH_via_gm.png

**Comment by danlipsa** [comment]
@doutriaux1 also, while some baselines are updated conda does not seem to download a new proj4.9.2? Do I have to do something? I tried reconfiguring and rebuilding but did not do anything.

**Comment by doutriaux1** [comment]
@danlipsa I pushed a fix that should force it to download proj4 4.9.2, let me know

**Comment by danlipsa** [comment]
@doutriaux1 Thanks. Now it works. I need to push a few alternate baselines, but I can do that in a separate PR. I'll merge.

**Comment by aashish24** [comment]
@danlipsa forgot to delete the branch?

**Pull request merged**
