### PR TITLE
Fix animate size.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 This fixes the animate tests - the problem was the size. Lets merge this quickly.

**Comment by aashish24** [comment]
since these test were broken before anyways, I am going to give it +1 without running it on my machine. 

LGTM :+1:

**Comment by doutriaux1** [comment]
@danlipsa @aashish24 this worires me. How did the `big` pictures got in? I suspect this means the size is computer dependent, no?

**Comment by danlipsa** [comment]
@doutriaux1 I think the big picture was the old size, the small picture is the default from testing.regression. The mac looks better than before only a few animate tests are failing, likely we need alternate baselines for those.

**Comment by danlipsa** [comment]
These are the tests failing on ubuntu 14.04
95% tests passed, 28 tests failed out of 611

Total Test time (real) = 396.32 sec

The following tests FAILED:
	 13 - testWrite (Failed)
	 62 - test_vcs_read_old_scr_2 (Failed)
	 73 - test_vcs_verify_boxfill_basics (Failed)
	121 - test_vcs_boxfill_decreasing_latitude (Failed)
	122 - test_vcs_meshfill_no_wrapping (Failed)
	413 - test_vcs_isofill_level0 (Failed)
	414 - test_vcs_isofill_level1 (Failed)
	415 - test_vcs_isofill_level2 (Failed)
	469 - test_vcs_matplotlib_colormap (Failed)
	549 - dv3d_vector_test (Failed)
	550 - dv3d_slider_test (Failed)
	551 - Hovmoller_volume_test (Failed)
	552 - dv3d_volume_test (Failed)
	553 - dv3d_constituents_test (Failed)
	554 - dv3d_surface_test (Failed)
	555 - dv3d_hovmoller_test (Failed)
	580 - cdms2_test_createcopy_lose_dtype (Failed)
	581 - CDMS_Test_01 (Failed)
	582 - CDMS_Test_02 (Failed)
	583 - CDMS_Test_03 (Failed)
	584 - CDMS_Test_04 (Failed)
	590 - CDMS_Test_10 (Failed)
	598 - CDMS_Test_18 (Failed)
	599 - CDMS_Test_20 (Failed)
	602 - CDMS_Test_write_compressed (Failed)
	606 - CDMS_Test_pack (Failed)
	609 - CDMS_Test_write_extended_dimension (Failed)
	610 - CDMS_Test_del_attributes (Failed)

**Comment by danlipsa** [comment]
These are the tests failing on mac os 10.11
94% tests passed, 38 tests failed out of 626

Total Test time (real) = 367.64 sec

The following tests FAILED:
	  3 - testMPIGrid (Failed)
	  4 - testAccuracy (Failed)
	  5 - testMarvel (Failed)
	  6 - testUnits (Failed)
	  7 - testRaynaud (Failed)
	  8 - testDateline (Failed)
	  9 - testEsmfInit4Pes (Failed)
	 17 - testMpi10Pes (Failed)
	 18 - testRemoteGet8Pes (Failed)
	 20 - testConserv (Failed)
	 21 - testEsmfVsLibcf (Failed)
	 22 - testEsmfInterface1 (Failed)
	 23 - testEsmfInterface2Pes (Failed)
	 24 - testDistArray6Pes (Failed)
	 25 - testGhostedDistArray6Pes (Failed)
	 26 - testEsmfGridToMeshRegridCsrv (Failed)
	 27 - testEsmf3DSmallesmf (Failed)
	 28 - testEsmf3DSmallesmf2Pes (Failed)
	 31 - testEsmfSmall2Pes (Failed)
	 32 - testEsmfSmall4Pes (Failed)
	 33 - testEsmfSmall8Pes (Failed)
	 35 - testTasRegrid2Pes (Failed)
	 46 - testEsmfSalinity2Pes (Failed)
	 47 - testEsmfSalinity4Pes (Failed)
	 48 - testEsmfSalinity8Pes (Failed)
	 52 - testDistSrc4Pes (Failed)
	 88 - test_vcs_verify_boxfill_basics (Failed)
	204 - test_vcs_legend_meshfill_horizontal_ext1_y_ext2_y (Failed)
	303 - test_vcs_basic_isofill_masked_aeqd_proj (Failed)
	318 - test_vcs_basic_isoline_0_proj_SH_gm (Failed)
	320 - test_vcs_basic_isoline_0_proj_SH_0_360_gm (Failed)
	417 - test_vcs_animate_projected_isofill_robinson (Failed)
	419 - test_vcs_animate_projected_boxfill_robinson (Failed)
	437 - test_vcs_animate_isoline_text_labels (Failed)
	438 - test_vcs_animate_isoline_text_labels_colored (Failed)
	483 - test_vcs_init_open_sizing (Failed)
	487 - test_vtk_ui_button_draw (Failed)
	607 - CDMS_Test_12 (Failed)

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 I think we should spend time fixing those - otherwise the list will keep growing.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Most problems are simple things like the hdf5 issue and filles that cannot be opened and alternate baselines.

**Comment by doutriaux1** [comment]
@danlipsa let's create a "travis" branch and fix all issues for linux and mac on this branch. The first thing to do will be to force hdf5=1.8.16 in the conda creation program. I have to finish a branch first before I can get to this tohugh.

**Comment by danlipsa** [comment]
@doutriaux1 Let me known when the hdf5 issue is done. This will fix a couple of tests. What is a travis branch?

**Comment by doutriaux1** [comment]
@danlipsa I started the `travis` branch, I actually called it `fix_travis` see: https://github.com/UV-CDAT/uvcdat/pull/2067

**Pull request merged**
