### PR TITLE
missing baseline files

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by sankhesh** [comment]
@doutriaux1 These files were also added in #71. The issue is the filenames are wrong. To avoid having duplicate files, please rename the existing ones.

**Comment by doutriaux1** [comment]
@sankhesh in the interest of time let's merge this and then remove the duplicate ones later. I can't spend too much time fixing these issues.

**Comment by sankhesh** [comment]
@doutriaux1 I fixed it.

**Comment by doutriaux1** [comment]
Thx!

**Pull request merged**
