### PR TITLE
Added new baselines

### PR DESCRIPTION
**Pull request by chaosphere2112**

### CODE REVIEW

**Comment by chaosphere2112** [comment]
Goes with UV-CDAT/uvcdat#1999

**Comment by doutriaux1** [comment]
@chaosphere2112 are you sure the anti-alias is OFF?

**Comment by chaosphere2112** [comment]
@doutriaux1 I'll regenerate them tomorrow, but I'm pretty sure these were made using the new 'testing.regression.init', so they really should be.

**Comment by chaosphere2112** [comment]
@doutriaux1 Yup, these were made with anti aliasing off. I just draw a lot of points for the circles :wink:

**Pull request merged**
