### PR TITLE
Baselines for Issue #1720 Data is clipped in interactive mode

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by aashish24** [comment]
@danlipsa looking much better. Why the new "test_vcs_animate_projected_meshfill_robinson.png" is clipped now and before it was not.

**Comment by danlipsa** [comment]
@aashish24 I just wanted to note that as well. I don't know. Probably it does something different than the rest of the projections.

**Comment by danlipsa** [comment]
I'll have to look into that.

**Comment by aashish24** [comment]
@danlipsa I don't think its only the projection. I think its the meshfill + projection issue. May be for the meshfill we need to treat the data as cell centered.

**Pull request merged**
