### PR TITLE
Remove gen grid point

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@danlipsa I will need to look at this carefully, at first glance it looks like the new baselines have much less details (smoother), I don't know if it's good or bad, but why is that?

**Comment by danlipsa** [comment]
@doutriaux1 This is because CellDataToPointData filter sets a point value from the average values for all cells that use the point.

**Comment by aashish24** [comment]
> @danlipsa I will need to look at this carefully

+1. I think we need to look at this very carefully. @danlipsa I asked for a image from  a pre-vtk version. Could you copy-paste it here so that we can compare and discuss? I am not suggesting that older version was correct.

**Comment by danlipsa** [comment]
Looks like the old image is very similar with the behavior of uvcdat before this commit.
Maybe it used cell centered data as point data the same as uvcdat did.
uvcdat-1 5 1

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Note that vtkCellDataToPointData does not do a simple average but does proper interpolation of the cell data to the points.

**Comment by doutriaux1** [comment]
@danlipsa sounds good, I will show these to a few scientists around here to get comments

**Comment by doutriaux1** [comment]
@danlipsa at first glance scientists here are VERY skeptical of the new method, it's  too smooth, they think we are probably losing important fetaures.  For the record here is what matplotlib does:
``python
import pylab as pl
pl.contourf(s,range(0,110,10))
pl.show()
```
![figure_1](https://cloud.githubusercontent.com/assets/2781425/14861604/d64fa254-0c62-11e6-8938-1d95f1acf1c7.png)

**Comment by doutriaux1** [comment]
@danlipsa I will build it locally and see how it does with higher resolution data. To be fai this model is at such a low resolution it's hard to tell what's going on.

**Comment by danlipsa** [comment]
@doutriaux1 What is s? Is that generated with the old code? In that case it should be the same as our previous images. What we changed was not the plotting method but how we generate s. I agree that the model is very low resolution so the high frequency changes we see might not be relevant.

**Comment by danlipsa** [comment]
@doutriaux1 Is there a way to generate the plots using continuous color map? The discontinuous color maps will enhance differences.

**Comment by aashish24** [comment]
@danlipsa we should be able to load clt dataset in paraview as well for comparison.

**Comment by doutriaux1** [comment]
@danlipsa yes `s` stands for `slab` and in this case it's our standard `clt` data

**Comment by doutriaux1** [comment]
@danlipsa why only files changed now? I thought because clt does not have bounds, most baselines would be affected. No?

**Comment by danlipsa** [comment]
@doutriaux1 I kept the traditional way of treating nc the default. I would rather introduce the new way gradually instead of changing 100+ baselines. Note:
+        plot_based_dual_grid = True | False          # Plot the actual grid or the dual grid based on what is
+                                                     # needed by the plot: isofill, isoline, vector need
+                                                     # point attributes, boxfill and meshfill need cell attributes
+                                                     # The default is True (if the parameter is not specified).
To get the new way you have to specify plot_based_dual_grid=False.

**Pull request merged**
