### PR TITLE
Additional baselines for Ubuntu 14.04

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@danlipsa did you run this on mac? Sometimes we need mac baselines.

**Comment by danlipsa** [comment]
@doutriaux1 No, this is on my ubuntu 14.04.

**Comment by doutriaux1** [comment]
ok i will run on my mac then.

**Comment by danlipsa** [comment]
@doutriaux1 LGTM 👍

**Pull request merged**
