### PR TITLE
better baseline

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
goes with: https://github.com/UV-CDAT/uvcdat/pull/1658

**Comment by aashish24** [comment]
@doutriaux1 how is better? Seems like default text has much larger background..

**Comment by doutriaux1** [comment]
this is not my doing @aashish24 it's actually @chaosphere2112 that "fixed" this it takes the width of the longest colormap name

**Comment by aashish24** [comment]
@doutriaux1 I see. so.. there are more entries in that drop down. sure, thanks. What else has changed?

**Comment by doutriaux1** [comment]
@aashish24 lots has changed now :wink: first of all the "initial.attributes" will only save the user-defined graphic method, that fastens tihngs a lot, that meant "recording" what is loaded as default and not re-store that. Also there were some issues in loading "old format" .scr initial.attribute files. I discovered these while converting one from Michael Wehner.

**Pull request merged**
