### PR TITLE
Changes to baselines based on new patterns

### PR DESCRIPTION
**Pull request by sankhesh**

### CODE REVIEW

**Comment by sankhesh** [comment]
Goes with UV-CDAT/vcs#23

**Comment by danlipsa** [comment]
@sankhesh I can still see some aliasing in the size of the lines.

**Comment by sankhesh** [comment]
@danlipsa Yes, it  is still a compromise between keeping the individual polygon size small but increasing the scale of the glyphs. Hopefully that will reduce with the distance to camera approach. For now, we can merge this as is.

**Comment by sankhesh** [comment]
@danlipsa @doutriaux1 @aashish24 I can't get the latest VTK to build on my machine. Could one of you please upload the new baselines for UV-CDAT/vcs#23 ?

**Comment by aashish24** [comment]
@sankhesh the new baselines are looking almost very pretty @doutriaux1 @williams13. It looks like that now I see consistent size of the patterns  (can you confirm?). There are very few instances that seems where the patterns overlap a bit (line ones). May be we can take of them in the next PR?

**Comment by sankhesh** [comment]
@aashish24 Yes, the rendered size is much better. I concur that we merge this branch and resolve any issues in a subsequent one.

**Comment by doutriaux1** [comment]
@aashish24 @sankhesh we are getting there. A few things I noticed (for example let's look at first plot: test_vcs_boxfill_hatch_SH_-180_180.png )
If you look at the legend
* 200-230 (and 300-310): last row of pattern and left-hand seem to have different transparency
* 230-240: checker pattern has thick lines (not appearing in plot which is good)
* 240-250: weird pattern
* 260-270 and 270-280: why are the lines not straight?
* 300-310: weird pattern

**Comment by sankhesh** [comment]
@doutriaux1 

Please find the corresponding pdf attached hereby.

[test_vcs_boxfill_hatch_SH_-180_180.pdf](https://github.com/UV-CDAT/uvcdat-testdata/files/771726/test_vcs_boxfill_hatch_SH_-180_180.pdf)

Screenshot of the rendered PDF:
colorbar

> - 200-230 (and 300-310): last row of pattern and left-hand seem to have different transparency

I don't see the different transparency effects in the PDF. Could it be coming from the png writer? @danlipsa @aashish24 - Any suggestions?

> - 230-240: checker pattern has thick lines (not appearing in plot which is good)

This issue is due to the fact that the color bar is rendered in a viewport that spans from 0.0 to 1.0. The scaling is off between the plot above and the color bar. Any suggestions on how to make the two scales match?

> - 240-250: weird pattern

I think this is again because of the PNG writer. I don't see the artifacts in PDF.

> - 260-270 and 270-280: why are the lines not straight?

Because of the weird scaling between the plot and the color bar. 

> - 300-310: weird pattern

Do you mean you don't like my super creative pattern? :cry: :disappointed: 

pattern

**Comment by aashish24** [comment]
> I don't see the different transparency effects in the PDF. Could it be coming from the png writer? @danlipsa @aashish24 - Any suggestions?

Hmm.. not really. Can you post the PNG and PDF here as well?

**Comment by aashish24** [comment]
> This issue is due to the fact that the color bar is rendered in a viewport that spans from 0.0 to 1.0. The scaling is off between the plot above and the color bar. Any suggestions on how to make the two scales match?

@sankhesh can you use the number from the main plot and scale it based on the viewport size of the color bar?

**Pull request merged**
