### PR TITLE
Baseline for new test for isoline label backgrounds

### PR DESCRIPTION
**Pull request by sankhesh**
Goes with UV-CDAT/uvcdat#1555

### CODE REVIEW

**Comment by sankhesh** [comment]
@doutriaux1 @durack1 @aashish24  Need this pull request to be merged as UV-CDAT/uvcdat#1555 is merged.

**Comment by durack1** [comment]
@chaosphere2112 do you have merge privileges for this repo?

**Comment by chaosphere2112** [comment]
@durack1 Sorry for the delay! Done.

**Comment by durack1** [comment]
@chaosphere2112 no problems - thanks..

**Pull request merged**
