### PR TITLE
Fix tests consistent names

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by danlipsa** [comment]
@aashish24 There are a few new failures after this merge:
	 65 - test_vcs_verify_proj_basics (Failed)
	 91 - test_remove_marker_none_1d (Failed)
	105 - test_vcs_wmo_markers (Failed)
Do you know anything about it?

**Comment by danlipsa** [comment]
@aashish24 These are all failures:
	 53 - test_vcs_read_old_scr_2 (Failed)
	 65 - test_vcs_verify_proj_basics (Failed)
	 91 - test_remove_marker_none_1d (Failed)
	105 - test_vcs_wmo_markers (Failed)
	424 - test_vcs_continents (Failed)
	561 - diags_test_02 (Failed)
	562 - diags_test_03 (Failed)
	563 - diags_test_04 (Failed)
	564 - diags_test_41 (Failed)
	565 - diags_test_05 (Failed)
	566 - diags_test_06 (Failed)
	567 - diags_test_07 (Failed)
	568 - diags_test_08 (Failed)
	569 - diags_test_09 (Failed)
	570 - diags_test_10 (Failed)
	571 - diags_test_11 (Failed)
	572 - diags_test_12 (Failed)
	573 - diags_test_13 (Failed)
	574 - diags_test_15 (Failed)

**Comment by doutriaux1** [comment]
vcs appears to be broken until we merge #1908

**Comment by danlipsa** [comment]
@doutriaux1 On my desktop and laptop all tests pass but:
424 - test_vcs_continents (Failed)
561 - diags_test_02 (Failed)
562 - diags_test_03 (Failed)
563 - diags_test_04 (Failed)
564 - diags_test_41 (Failed)
565 - diags_test_05 (Failed)
566 - diags_test_06 (Failed)
567 - diags_test_07 (Failed)
568 - diags_test_08 (Failed)
569 - diags_test_09 (Failed)
570 - diags_test_10 (Failed)
571 - diags_test_11 (Failed)
572 - diags_test_12 (Failed)
573 - diags_test_13 (Failed)
574 - diags_test_15 (Failed)
which have been broken for a while.

**Comment by doutriaux1** [comment]
yes the diags are right in another branch I believe

**Pull request merged**
