### PR TITLE
Baselines for: BUG #1265: Fix datawc zoom-in for geographic projections.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@danlipsa I'm about to submit a PR for the new default colormap, it updates EVERY baselines pretty much. Do you mind if we merge this one after?

**Comment by danlipsa** [comment]
@doutriaux1 No, I don't. Go ahead. I can regenerate my baselines.

**Comment by doutriaux1** [comment]
The following look weird:
https://github.com/UV-CDAT/uvcdat-testdata/blob/689fd0a5ca31ed737a33b86821dfd16d09788f57/baselines/vcs/test_vcs_basic_isofill_masked_aeqd_proj.png

**Comment by danlipsa** [comment]
Yes, I have an issue about it:
https://github.com/UV-CDAT/uvcdat/issues/2099
For certain aeqd tests, we still get two layers of cells in the front or back. We might be able to fix this with a new proj4.

**Pull request merged**
