### PR TITLE
Baselines and test file for BUG #5: vtkPolyData::RemoveDeletedCells d…

### PR DESCRIPTION
**Pull request by danlipsa**
…oes not remove GlobalIds or points.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@danlipsa why did the size of the arrows change?

**Comment by doutriaux1** [comment]
@aashish24 we relaly really really need to have the vector legend put back in, otherwise the vector plots are kind of useless

**Comment by danlipsa** [comment]
@doutriaux1 It actually restores the baseline before datawc changes:
git diff f628f2fbab166e9454747f4d7e4dcd53a4487465..HEAD ./baselines/vcs/test_vcs_vectors_missing.png
will show very little differences.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Regarding vector legend - I never seen a vector legend in charts - I assume because it is difficult to visually compare lengths of segments. Maybe a workaround would be to display information related to the vector magnitude (max, mean, min). I think what is displayed now is something else: Min=-16 for  test_vcs_vectors_missing.png

**Comment by doutriaux1** [comment]
@danlipsa for wind for example we need to know what the length of the arrow means, especially since you can apply a scale factor to your graphic method. Look at old picture using vcs 1.5 they had a legend, i.e. a small arrow and it would say how much this arrow represent in term of sqrt(x*x+y*y) units. Does it make sense?

**Comment by doutriaux1** [comment]
@danlipsa diags test do pass again, I'm going to go ahead and merge this. Thanks!

**Comment by danlipsa** [comment]
> diags test do pass again, I'm going to go ahead and merge this. Thanks!
Great! Thanks!

> for wind for example we need to know what the length of the arrow means, especially since you can apply a scale factor to your graphic method. Look at old picture using vcs 1.5 they had a legend, i.e. a small arrow and it would say how much this arrow represent in term of sqrt(xx+yy) units.

Do you have a link or can you attach a picture?
My comment on a vector legend is that 1. It is difficult to compare the vectors in the legend with the vectors in the picture, especially if the vectors in the picture do not have the same orientation as the vectors in the legend 2. I never seen a vector legend (ParaView does not have one) and I wonder if the reason might be listed in 1. If you want to see sizes in ParaView you can color the vectors by vector magnitude, or show vector magnitude as a scalar and color map that.

**Comment by danlipsa** [comment]
@doutriaux1 Showing (min, max and average) for the vector magnitude would provide roughly the same information as the legend.

**Comment by danlipsa** [comment]
@doutriaux1 I distinctly remember comments to one of my papers where I attempted a vector legend: people did not understand that, and also complained it is non-standard. :smile:

**Comment by doutriaux1** [comment]
@danlipsa I like the color idea! But even then you need a colorbar.
In the mean time here is picture example.
vector

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 This 'vector bar' does not look that good, and the information can be deduced from the Max value. We could add an option to the vector plot to create and plot a scalar representing the vector magnitude (isofill?) - this will give us the color bar showing the magnitude information and will look better.
What do you think?

**Pull request merged**
