### PR TITLE
Viridis latest

### PR DESCRIPTION
**Pull request by doutriaux1**
new baselines for viridis

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 Here are my comments on the changes:
- The *transparent* images are different. Yours look better, but I am not sure they are correct. Did you put in a fix for this?
- boxfill_decreasing_latitude has a yellow on both the left and the right of the color bar. Should the yellow on the right be white?
- Should the *hatch* tests colors be changed? They did not seem to be in the rainbow color initially.
 The same for boxfill_solid_. The problem with changing the color map for those is that the new color map seems to have colors which are very close (shades of yellow)
- colorpicker_appearance looks different
- hatches_patterns has many shades of yellow
- *iso_celine_* changes white into blue, but white is special in cdat
- the default line color for isoline was blue, now it is yellow - this is a strange choice. Should stay blue or become black. For instance in isoline_extent_attributes
- The choice for label color should not change, for instance in isoline_labels_multi_label_input_types
- test_vcs_markers were red, green, blue, red now they are all shades of yellow
- missing_color_name shows some green vertical bars which now look like the rest of the colors in the palette.
- taylor_template_ctl had grey lines, now those lines are yellow
- wmo_markers were red, now are yellow
- addons_polar_seasonal used categorical colors, now they use viridis

**Comment by doutriaux1** [comment]
@danlipsa 
* transparent, yes it's better now because the color of the lines are now fixed as "black" (0,0,0,100) so setting the transparency of the allthe color of the palette does not matter for these any more (they used to point to 1 or 241)
* boxfill_decreasing: The test sets the `left color` to 240 which used to be white, is it what you mean? I changed the test to set it to `white` not 240
* hatch test reverted to use classic colormap
* colorpicker ??? Not sure what to say here @chaosphere2112 do you know what Dan means?
* celine: double twaek: made sure white is [100,100,100,0] in celine.json and also reverted to older colormap
* default line for isoline was and is and should be black, i took great care making sure it is all updated, please remove your initial.attribute from your ${HOME}/.uvcdat I think that's what is causing the issue, let me know if you still see blue or yellow. Colored isolines now are suing `viridis` in test, I actually like them better now.
* isoline labels color, I don't think it matters what the color is they are tested in the test filess, as long they are not black I think we're good.
* missing_Colorname now uses lightgrey for colorname
* taylor now back to grey
* wmo it doesn't matter red or yellow
* polar addons color do not matter according to @chaosphere2112 
all this in commit: 284bf933e3aa359be7702aa6fcf8c8148d6a3b1e and ae90e915a2cf661b4e9a94f02d401239f0c844ff

**Comment by danlipsa** [comment]
@doutriaux1 Second pass:
- boxfill_hatch_SH_-180_180_non_contig, boxfill_solid_SH_-180_180_non_contig, isofill_hatch_SH_-180_180_non_contig,  isofill_solid_SH_-180_180_non_contig, meshfill_hatch_SH_-180_180_non_contig, meshfill_solid_SH_-180_180_non_contig prev image has a triangle for 320 current one has a rectangle
- boxfill_hatch_SH_-180_180_non_contig_1,  isofill_hatch_SH_-180_180_non_contig_1,  isofill_solid_SH_-180_180_non_contig_1, meshfill_hatch_SH_-180_180_non_contig_1 should be removed
- colorpicker_appearance what I meant is that at the top, the old image has many colors (categorical color map) the new image has only yellow
- fillarea_transparency the new image changes purple to grey. Not sure it is relevant.
- isoline_extend_attributes still blue changed to yellow

**Comment by doutriaux1** [comment]
@danlipsa it should be a rectangle, arrows are for `greater_than`
yes there are a lot of _1 that needs removing (I hope that eventually we do not need any _1 or _2) do you mind doing this?
colorpicker, I don't think the test cares about the actual color, we're just testing that it can pick the color right @chaosphere2112 ?
fillarea transparency, is good, just using different colors now
isoline_extend_attributes is yellow because color 250 is now yellow.
I think we are good to merge.

**Comment by danlipsa** [comment]
@doutriaux1 Sounds good. I'll wait for the buildbot to finish and then merge.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 @sankhesh Our viridis in the colorbar seems to show less yellow than the viridis on matplotlib page:

https://github.com/UV-CDAT/uvcdat-testdata/blob/7927934ea553a4c3e9edda096d483a49f105961a/baselines/vcs/first_png_blank.png

http://matplotlib.org/examples/color/colormaps_reference.html

**Comment by doutriaux1** [comment]
@aashish24 you added `viridis` to vcs, can you double check?

**Comment by doutriaux1** [comment]
@danlipsa Also I think our graphic methods only use 16,240 as the default range.

**Comment by danlipsa** [comment]
@doutriaux1 I see, probably that is the reason. @aashish24 showed me his js that showed the color maps and the vcs and matplotlib looked the same. It is strange though - you would expect to have the full viridis not a truncated one. Anything we can do?

**Comment by doutriaux1** [comment]
that would seriously break backward compatibility. IN the old times, colors 0 thru 16 and 240 to 255 where reserved so that a user could always get "red"/"blue", etc... Now we can reset any color in the colormap and use rgb/names to set a color so it is not an issue anymore. Keep in mind that using the full range will make every existing `vc` (as in not from matplotlib) look horrible.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Maybe we can fit the full viridis in 16 to 240? That might be better than  having the bottom and top cut of.

**Comment by doutriaux1** [comment]
let's open another issue for this problem.

**Comment by danlipsa** [comment]
@doutriaux1 They only problem would be that this other issue will replace all baselines as well. :smile: But, yeah lets do that.

**Comment by danlipsa** [comment]
@aashish24 What do you think? Should we release a truncated viridis?

**Comment by doutriaux1** [comment]
for now one can use the full viridis by doing
```python
import vcs
x=vcs.init()
iso = vcs.createisofill()
levels = range(0,110,10)
cols = vcs.getcolors(levels,colors=range(256))
iso.levels=levels
iso.fillareacolors=cols
x.plot(s,iso)
```
full

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Actually, we won't release this, just merge into master and follow up with an update that fixes viridis in cdat, isn't it?

**Comment by doutriaux1** [comment]
sounds right, but now I"m wondering if we shouldn't change our default to use the full colormap....

**Comment by danlipsa** [comment]
@doutriaux1 If it is not too difficult, I would do that.

**Comment by doutriaux1** [comment]
yes I think I'm going to add this, older scripts will need tweaking though...

**Comment by doutriaux1** [comment]
talked to @williams13 he agrees we should change the defaults. I'll be doing this on Monday. As I'm off Friday and on another project today.

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa so we will change the default to "not use full colormap" (16-240) is that right?

**Comment by doutriaux1** [comment]
@aashish24 no the new default is to use the full colormap

**Comment by aashish24** [comment]
> @aashish24 no the new default is to use the full colormap

+1 but how it is going to work out for other coloamaps which has reserved 1-16 and 240-255 for example?

**Pull request merged**
