### PR TITLE
Add baselines for streamline graphics method.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@danlipsa shouldn't streamlines have arrows?

**Comment by glpotter** [comment]
The colors seem to be working but is there a way to even out the space between streamlines? They don't have to be equally spaced but just more like the examples that @durack1 and I posted. Is the velocity related to the spacing as well as the color?

**Comment by danlipsa** [comment]
@glpotter The distance between streamlines does not stay constant, so lines that start far apart can get close together. Right now the seeds (the starting points of streamlines) are chosen randomly in the dataset. One can control the number of seeds to control the look. Another possibility is to do uniform seeding. In my experience random seeding looks better than uniform seeding but we can try uniform seeding as well.

Only color is related to velocity. The empty space is a result of the seed placement and vector field.

**Comment by glpotter** [comment]
@danlipsa Can we try it now?

**Comment by danlipsa** [comment]
@glpotter Yes, everything should work nicely. Please coordinate with @doutriaux1. We'll need to merge this and build new conda packages. You can try this from source but it is more involved as this needs a new VTK as well.

**Pull request merged**
