### PR TITLE
Duplicate longitude wrap

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
test_vcs_animate_projected_boxfill_polar.png is rotated because the new code sets the lon_0 (central meridian) to (-180 + 175) / 2 which is different than 0. I think the other polar plots are rotated because of the same reason.

**Comment by danlipsa** [comment]
Similarly test_vcs_animate_projected_meshfill_mollweide.png also appears to be affected by setting of lon_0.

**Comment by danlipsa** [comment]
@aashish24 @chaosphere2112 meshfill dataset varies from -40 to 361. It is not clear to me why the portion from -40 to 0 is missing from the plot. This may be a bug in proj4. It would be interesting to test this with the new proj4. Aashish, how is upgrading to the new proj4 going?

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Any of you know why for sampleCurveGrid4.nc bounds_lat and bounds_lon have an additional parameter nvert = 4? I would have expected 2 bounds not 4.

**Comment by aashish24** [comment]
I believe its because its a curvelinear grid and each cell requires four vertices.. but I could be wrong about it.

**Comment by danlipsa** [comment]
bounds_lat has 4 points as well. I would have expected 2 for lon and 2 for lat.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 boxfill changes we see are because data range varies from -182.5 to 177.5 which results in an extra row on left and also the central meridian being moved from 0 to -2.5

**Comment by doutriaux1** [comment]
@danlipsa `nvert` is the number of vertice per cell. So 4 makes sense here. Curvilinear grid.

**Comment by danlipsa** [comment]
@doutriaux1 Oh, I see. So each point can have a different lat/lon.

**Comment by doutriaux1** [comment]
yes it can, it could be any shape too, like stars or anything example: https://www.myroms.org/links/newbad.png

**Comment by jypeter** [comment]
@danlipsa you can check the values of lon and lat in https://github.com/UV-CDAT/uvcdat/issues/1465#issuecomment-133473257 as another example. And this is a data file where unfortunately the cell boundary data is missing (but basemap can still make a decent plot)

**Comment by doutriaux1** [comment]
@aashish24 @jypeter that's another issue. Probably post release

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Regarding the meshfill plots, it seems that sampleCurveGrid4.nc has very few points/cells below longitude -10 and all seem to be at high latitude.
This matches the projection we see with most values between lon -40 and 0 empty.
A side note is that it would be a worthwhile endeavor to upgrade the nc reader in ParaView to be able to read bounds. Then it would make it much easier/faster to debug uvdat on any customer's data.

I added a breakpoint in vcs2vtk.genGrid and printed a slice from data2 (which seems to be the bounds data). data2.shape is (1536,2,4)
 p data2.data[numpy.any(data2[:,1] < -10, 1).data,:,:]
array([[[  71.20559511,   73.804111  ,   76.34111219,   73.65918693],
        [  -2.0933775 ,    5.54460936,   -9.12835156,  -14.18136947]],

       [[  78.98636229,   81.57617148,   82.41927318,   79.95552707],
        [  -3.28731527,    4.14292241,  -25.08277799,  -24.86542329]],

       [[  81.57617148,   84.06203095,   84.82266859,   82.41927318],
        [   4.14292241,   15.22514943,  -28.10941667,  -25.08277799]],

       [[  84.06203095,   86.26519018,   87.07516919,   84.82266859],
        [  15.22514943,   36.57806873,  -40.359316  ,  -28.10941667]],

       [[  86.26519018,   87.37999805,   88.42000205,   87.07516919],
        [  36.57806873,   85.0000674 ,  264.9999046 ,  -40.359316  ]]])

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 This finding matched the baseline test_vcs_animate_projected_meshfill_lambert.png

**Pull request merged**
